recipes-libraries: deepview-rt: add append to fix compilation issue
We bbappend deepview-rt recipes to add requires native missing package
just add the following variable:

PACKAGE_ARCH = "${MACHINE_SOCARCH}"

This fix the following compilation issue deepview-rt_2.4.46-aarch64.bb
recipe:

ERROR: deepview-rt-2.4.46-aarch64-r0 do_package_qa: QA Issue: /usr/lib/python3.10/site-packages/bin/deepview-modelclient contained in package deepview-rt requires /workdir/build-imx8mp/tmp/work/armv8a-poky-linux/deepview-rt/2.4.46-aarch64-r0/recipe-sysroot-native/usr/bin/nativepython3, but no providers found in RDEPENDS:deepview-rt? [file-rdeps]
ERROR: deepview-rt-2.4.46-aarch64-r0 do_package_qa: Fatal QA errors were found, failing task.
ERROR: Logfile of failure stored in: /workdir/build-imx8mp/tmp/work/armv8a-poky-linux/deepview-rt/2.4.46-aarch64-r0/temp/log.do_package_qa.878020
ERROR: Task (/workdir/sources/meta-imx/meta-ml/recipes-libraries/deepview-rt/deepview-rt_2.4.46-aarch64.bb:do_package_qa) failed with exit code '1'

References:
 - meta-imx/meta-ml/recipes-libraries/deepview-rt/deepview-rt_2.4.46-aarch64.bb

Signed-off-by: Tommaso Merciai <tommaso.merciai@avnet.com>